### PR TITLE
Update and fix tests

### PR DESCRIPTION
**Pull request by cap10morgan**
OK, here's the story:

I was strolling along, updating datomic and other simple housekeeping things in the project.clj files as a part of [this card](https://www.pivotaltracker.com/story/show/110658064). When I got to this project I noticed it had a non-standard logging config so I fixed it up. But then I noticed that when I turned off log output in the tests (which greatly improves the signal:noise ratio there), it broke a test. I didn't love that so I played around with a different approach that would allow us to set test expectations about log messages but be less dependent on the global logging configuration, level, etc.

This is the result.

### CODE REVIEW

**Comment by cap10morgan** [comment]
UPDATE: @ddellacosta Looks like you wrote the original "log a warning" call for missing election authorities. @tie-rack and I were wondering why that wasn't just throwing an exception instead (which is then caught by `handle-errors` and logged as an error).

I've changed it to do that (and removed the test stubbing stuff since it is no longer necessary) in the latest commit.

But please consider all of this still up for discussion (as is anything in a PR).

**Comment by ddellacosta** [comment]
@cap10morgan So the entire point of this was to avoid the noise we were getting in logs from missing election-authority exceptions (https://github.com/democracyworks/election-mail-works/pull/13), which was obscuring other presumably more critical exceptions.  We could get rid of this test but I think that the real solution is to refactor this code so that we have something we can test, or take a step back and ask why we weren't getting election-authorities in the first place and address that at the source.  Either way I don't think we are gaining much here other than adding the noise back that we had previously...maybe let's get some other folks input here too? ( @tank157 do you have thoughts? )

**Comment by cap10morgan** [comment]
Hmm, in that case I think we attacked the wrong part of the problem. Having too many errors in Slack shouldn't motivate us to downgrade them to warnings (unless they _really_ should have been warnings all along; which doesn't seem to be the case here but maybe I'm misunderstanding something?). Instead it should motivate us to fix the actual problem, even if it's hard and/or time-consuming.

What happens from a user's perspective when an electorate is missing the authorities? Do we have any theories as to what's causing it?

Until we fix the root cause, I think we _should_ be bugged about it continuously in Slack as a reminder that it is still broken.

**Comment by cap10morgan** [comment]
@ddellacosta @tank157 Any thoughts on this one?

**Comment by tank157** [comment]
I haven't had any spare cycles to look into this, sorry.

**Comment by cap10morgan** [comment]
@ddellacosta @tank157 Have things quieted down enough to get this merged before end of sprint?

**Comment by ddellacosta** [comment]
@cap10morgan Sorry I never responded Wes. I have no objections to simply reverting this. Would still appreciate hearing what Troy has to say though.

**Comment by tank157** [comment]
My thoughts are that the causes of missing authorities are many and varied and often not under our control (be they issues with Google, issues with imperfect matching algorithms, users inputting bad and/or junk data, etc). We've made some concessions already (see the addition of the state level ocd-id generated by the address state, for example) to be able to provide *some* services to users, so it seems like it's already considered not to be a catastrophic error when the matching fails for some reason. I think a warning isn't out of the question here, but I also think we need to be implementing more things to try and deal with these cases sooner (ie confirmation workflows, address pre-fills, etc).

**Comment by cap10morgan** [comment]
Finally circling back to this. What do you think of that last commit, @ddellacosta and @tank157?

**Comment by tank157** [comment]
👍

**Comment by ddellacosta** [comment]
👍 here too

**Comment by ddellacosta** [comment]
Although I am sad my incredible log output tester is going away, that thing was a work of art, albeit blasphemous art

**Pull request merged**
